### ISSUE TITLE
Not coming up in Firefox

### ISSUE THREAD

**Issue by g7sim** [manu37/tinymce5#4]
I installed tinymce5 in the plugins-directory. In Edge and Chrome it comes up (without entry of an api-key) , but in newest firefox(xampp)  i get : tinyMCE not present! Either offline or local library missing.

https://cloud.tinymce.com/5/tinymce.min.js?apiKey=v5izxlywdkhoajzvg9js1hlvawd3cxd727vizn72kilpwidv functions in firefox. To copy this tinymce.min.js (5.2.2-80) into the tinymce5\tinymce-directory doesnt solve it.

**P.S. Solved** : In firefox i must copy the tinymce.min as above and remove the hook from CDN - this should also function in the other browsers( hope i didnt abuse Your apikey...)

* <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> this version has nearly the same size , just as
* https://cdn.tiny.cloud/1/invalid-api-key/tinymce/5.2.2-80/tinymce.min.js
* There is also **https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.3.1/tinymce.min.js** (much smaller)

**Comment by manu37** [comment]
As it is/was a preview plugin I never thought till now about to use the locally stored version. Since versions are still rolled out more often than monthly I wait for a locally installed version.  I left my personal API key in the code by mistake. It runs only on domains by me, eventually on localhost. How to get your free API key or draw your local version is mentioned [here](https://www.tiny.cloud/get-tiny/).
